/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDisplayData: typeof import('./src/components/AppDisplayData.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    AppRGB: typeof import('./src/components/AppRGB.vue')['default']
    GlowBorder: typeof import('./src/components/GlowBorder.vue')['default']
    IconTonConnect: typeof import('./src/components/IconTonConnect.vue')['default']
    MyTabbar: typeof import('./src/components/MyTabbar.vue')['default']
    NoRecord: typeof import('./src/components/NoRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnowfallBg: typeof import('./src/components/SnowfallBg.vue')['default']
    TestLogin: typeof import('./src/components/TestLogin.vue')['default']
    UserAvatr: typeof import('./src/components/UserAvatr.vue')['default']
    UserBalance: typeof import('./src/components/UserBalance.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
